# Generated by Django 4.2.7 on 2024-05-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='identifier',
            field=models.CharField(default=150, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
