# Generated by Django 4.2.7 on 2024-06-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_collection_deleted_item_deleted_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images'),
        ),
    ]
